api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "cart-transformer-2"
uid = "0e44597a-9283-ecee-c1c5-aad447c4fff555693f6f"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
