# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2f1aa141c1e326a85cf74a78470bf86b"
name = "hdc-digital-app"
handle = "hdc-digital-app"
application_url = "https://receipt-italiano-layer-routine.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = ["https://receipt-italiano-layer-routine.trycloudflare.com/auth/callback", "https://receipt-italiano-layer-routine.trycloudflare.com/auth/shopify/callback", "https://receipt-italiano-layer-routine.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
